### ISSUE TITLE
Error in compilation 

### ISSUE THREAD

**Issue by Just-AndyE** [Tinyu-Zhao/INA3221#2]
I receive this error when i try to compile my code for Digispark board.

`cannot convert 'USI_TWI*' to 'int*' for argument '1' to 'void INA3221::begin(int*)'

On my arduino board code compiles OK.

**Comment by TinyuZhao** [comment]
<img width="1113" alt="image" src="https://github.com/Tinyu-Zhao/INA3221/assets/44396641/5a08d8c0-c018-4c7d-8f45-722aa31e9f40">
There is no such thing as USI_TWI* in the entire INA3221 library, and you have provided too little information for me to help you at this time.
